// Module: PAGES['parent_leaves']
export function registerPage(PAGES) {
  PAGES['parent_leaves'] = function() {
  var child = window.parentChildren[window.currentChildIdx] || window.parentChildren[0];

  return '<div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:20px">'
    + '<div>'
    + '<div style="font-size:20px;font-weight:800;color:var(--text)">📝 Leave Requests & Absence Portal</div>'
    + '<div style="font-size:13px;color:var(--muted)">Manage student leave applications and view attendance records</div>'
    + '</div>'
    + '<button class="btn btn-solid" style="background:linear-gradient(135deg,#10b981,#059669)" onclick="window.openApplyLeaveModal()">📝 Apply for Leave</button>'
    + '</div>'
    + '<div style="display:grid;grid-template-columns:1fr 2fr;gap:20px">'
    + '<div class="card">'
    + '<div class="card-header"><div class="card-title">📊 Attendance Summary</div></div>'
    + '<div style="text-align:center;padding:20px 0">'
    + '<div style="font-size:42px;font-weight:800;color:#10b981">' + child.att + '%</div>'
    + '<div style="font-size:12px;color:var(--muted);margin-top:4px">Total Attendance this Term</div>'
    + '</div>'
    + '<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;text-align:center;border-top:1px solid rgba(255,255,255,0.08);padding-top:14px;margin-top:10px">'
    + '<div><div style="font-size:16px;font-weight:700;color:#4ade80">42</div><div style="font-size:11px;color:var(--muted)">Present</div></div>'
    + '<div><div style="font-size:16px;font-weight:700;color:#ff2d6b">2</div><div style="font-size:11px;color:var(--muted)">Absent</div></div>'
    + '<div><div style="font-size:16px;font-weight:700;color:#fbbf24">1</div><div style="font-size:11px;color:var(--muted)">Leave</div></div>'
    + '</div></div>'
    + '<div class="card">'
    + '<div class="card-header"><div class="card-title">📋 Leave Application History</div></div>'
    + '<div style="display:grid;gap:12px">'
    + '<div class="leave-card">'
    + '<div style="display:flex;justify-content:space-between;align-items:center">'
    + '<div style="font-weight:700;font-size:14px">Family Medical Emergency</div>'
    + '<span class="status-approved">✓ Approved</span>'
    + '</div>'
    + '<div style="font-size:12px;color:var(--muted);margin-top:6px">Dates: <b>March 20, 2026 – March 22, 2026</b> (3 Days)</div>'
    + '<div style="font-size:11px;color:var(--muted);margin-top:4px">Applied on: March 18, 2026 by Suresh Sharma</div>'
    + '</div>'
    + '<div class="leave-card">'
    + '<div style="display:flex;justify-content:space-between;align-items:center">'
    + '<div style="font-weight:700;font-size:14px">Attending State Level Quiz Contest</div>'
    + '<span class="status-pending">⏳ Pending Approval</span>'
    + '</div>'
    + '<div style="font-size:12px;color:var(--muted);margin-top:6px">Dates: <b>March 25, 2026 – March 26, 2026</b> (2 Days)</div>'
    + '<div style="font-size:11px;color:var(--muted);margin-top:4px">Applied on: March 21, 2026 by Suresh Sharma</div>'
    + '</div>'
    + '</div></div>'
    + '</div>';
};
}
