// Central Page Registry Loader
import { registerPage as reg0 } from './student/dashboard.js';
import { registerPage as reg1 } from './student/courses.js';
import { registerPage as reg2 } from './student/videos.js';
import { registerPage as reg3 } from './shared/live.js';
import { registerPage as reg4 } from './student/tests.js';
import { registerPage as reg5 } from './student/material.js';
import { registerPage as reg6 } from './student/doubts.js';
import { registerPage as reg7 } from './student/announcements.js';
import { registerPage as reg8 } from './student/profile.js';
import { registerPage as reg9 } from './student/progress.js';
import { registerPage as reg10 } from './student/attendance.js';
import { registerPage as reg11 } from './student/leaderboard.js';
import { registerPage as reg12 } from './student/fees.js';
import { registerPage as reg13 } from './student/feedback.js';
import { registerPage as reg14 } from './faculty/dashboard.js';
import { registerPage as reg15 } from './faculty/batches.js';
import { registerPage as reg16 } from './faculty/content.js';
import { registerPage as reg17 } from './faculty/live.js';
import { registerPage as reg18 } from './faculty/tests.js';
import { registerPage as reg19 } from './faculty/tracker.js';
import { registerPage as reg20 } from './faculty/analytics.js';
import { registerPage as reg21 } from './faculty/doubts.js';
import { registerPage as reg22 } from './faculty/reports.js';
import { registerPage as reg23 } from './faculty/feedback.js';
import { registerPage as reg24 } from './admin/dashboard.js';
import { registerPage as reg25 } from './admin/users.js';
import { registerPage as reg26 } from './admin/courses.js';
import { registerPage as reg27 } from './admin/fees.js';
import { registerPage as reg28 } from './admin/reports.js';
import { registerPage as reg29 } from './admin/attendance.js';
import { registerPage as reg30 } from './admin/notifications.js';
import { registerPage as reg31 } from './admin/announcements.js';
import { registerPage as reg32 } from './admin/profile.js';
import { registerPage as reg33 } from './faculty/profile.js';
import { registerPage as reg34 } from './admin/settings.js';
import { registerPage as reg35 } from './admin/media.js';
import { registerPage as reg36 } from './admin/approvals.js';
import { registerPage as reg37 } from './admin/quiz.js';
import { registerPage as reg38 } from './admin/payments.js';
import { registerPage as reg45 } from './shared/journey.js';
import { registerPage as reg46 } from './shared/badges.js';
import { registerPage as reg47 } from './shared/qbank.js';
import { registerPage as reg48 } from './shared/fees.js';
import { registerPage as reg49 } from './shared/doubts.js';
import { registerPage as reg50 } from './shared/saas.js';
import { registerPage as reg51 } from './shared/inhouse.js';

export function registerAllPages(PAGES) {
  reg0(PAGES);
  reg1(PAGES);
  reg2(PAGES);
  reg3(PAGES);
  reg4(PAGES);
  reg5(PAGES);
  reg6(PAGES);
  reg7(PAGES);
  reg8(PAGES);
  reg9(PAGES);
  reg10(PAGES);
  reg11(PAGES);
  reg12(PAGES);
  reg13(PAGES);
  reg14(PAGES);
  reg15(PAGES);
  reg16(PAGES);
  reg17(PAGES);
  reg18(PAGES);
  reg19(PAGES);
  reg20(PAGES);
  reg21(PAGES);
  reg22(PAGES);
  reg23(PAGES);
  reg24(PAGES);
  reg25(PAGES);
  reg26(PAGES);
  reg27(PAGES);
  reg28(PAGES);
  reg29(PAGES);
  reg30(PAGES);
  reg31(PAGES);
  reg32(PAGES);
  reg33(PAGES);
  reg34(PAGES);
  reg35(PAGES);
  reg36(PAGES);
  reg37(PAGES);
  reg38(PAGES);
  reg45(PAGES);
  reg46(PAGES);
  reg47(PAGES);
  reg48(PAGES);
  reg49(PAGES);
  reg50(PAGES);
  reg51(PAGES);
}
